Models/StockItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Models
{
    public class StockItem
    {

        [Key]
        public Guid StockId { get; set; }

        [MaxLength(20)]
        [Display(Name = "GRN No.")]
        public string GRNNo { get; set; }

        public virtual Product Product { get; set; }

        [ForeignKey("ProductId")]
        [Required]
        [Display(Name = "Product")]
        public Guid? ProductId { get; set; }

        public virtual Location Location { get; set; }

        [ForeignKey("LocationId")]
        [Display(Name = "Location")]
        public Guid? LocationId { get; set; }

        [MaxLength(100)]
        [Display(Name = "Serial No.")]
        public string SerialNo { get; set; }

        [MaxLength(100)]
        [Display(Name = "Batch No.")]
        public string BatchNo { get; set; }

        [Display(Name = "Date Received")]
        public DateTime DateReceived { get; set; }

        [MaxLength(100)]
        [Display(Name = "Received By")]
        public string ReceivedBy { get; set; }

        [Required]
        [Display(Name = "InitialQty")]
        public decimal InitialQty { get; set; }

        [Required]
        public decimal QtyAvailable { get; set; }

        [Required]
        [Display(Name = "Cost Per UOM")]
        public Decimal CostPerUOM { get; set; }

        [Required]
        [Display(Name = "Total Cost")]
        public Decimal TotalCost { get; set; }

        public string Notes { get; set; }

        public Guid SiteId { get; set; }

    }
}

Controllers/LocationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Location Methods throughout the app.
    /// </summary>
    public class LocationsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public LocationsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Location View.
        /// </summary>
        /// <returns>Add Location View</returns>
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid.  Method then get the User and Site Id and creates a new Location for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Location View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(Location model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddLocation(model);
                ModelState.Clear();
                return RedirectToAction("list", new { id = "success" });
            }

            return View();
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Location ID and Site Id and loads the data into a Category Model and passes the Model into the Edit Location View for edit.
        /// </summary>
        /// <returns>Edit Category View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();
                Location model = _repository.GetLocation(key, siteId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Location View</returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(Location model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveLocation(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Location data grid.
        /// </summary>
        /// <returns>Location List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllLocations(siteId);
            return View(data);
        }

        #endregion
      
    }
}

Controllers/StockItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Stock Receipt Methods throughout the app.
    /// </summary>
    public class StockItemsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public StockItemsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Stock data grid.
        /// </summary>
        /// <returns>Stock Receipt List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllAvailableStock(siteId);
            return View(data);
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Stock ID and Site Id and loads the data into a Stock Items Model and passes the Model into the Edit Stock View for edit.
        /// </summary>
        /// <returns>Edit Category View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();

                StockItem model = new StockItem();
                model = _repository.GetStockItem(key, siteId);

                //Loads the dropdown data
                ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name", model.LocationId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Stock Item Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Stock Item View</returns>
        [Authorize]
        [HttpPost]
        public ActionResult Edit(StockItem model)
        {
            model.Product = null;
            ModelState.Clear();
            TryValidateModel(model);
            if (ModelState.IsValid)
            {
                _repository.SaveStockItem(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

    }
}

Views/StockItems/Edit.cshtml
@model Stockzilla.Models.StockItem
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Edit Stock - Stockzilla";
    ViewBag.Header = "Edit Stock";
}
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 col-md-offset-3">
    <form method="post" novalidate>
        @Html.HiddenFor(model => model.StockId)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.SiteId)

        <div class="form-group">
            @Html.LabelFor(model => model.GRNNo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.GRNNo, new { @class = "form-control", @placeholder = "GRN No.", @readonly = "readonly" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.Product.ProductCode, new { @class = "form-control", @placeholder = "Product Code", @readonly = "readonly" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, new { @class = "control-label" })
            <div class="input-group">
                @if (Model.LocationId != null)
            {
                    @Html.DropDownList("LocationId", null, "Choose Location", new { @class = "form-control", value = Model.Location.Name })
                }
                else
                {
                    @Html.DropDownList("LocationId", null, "Choose Location", new { @class = "form-control" })
                }
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Locations")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SerialNo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.SerialNo, new { @class = "form-control", @placeholder = "Serial No." })
            @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BatchNo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.BatchNo, new { @class = "form-control", @placeholder = "Batch No." })
            @Html.ValidationMessageFor(model => model.BatchNo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.InitialQty, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.InitialQty, new { @class = "form-control", @placeholder = "Initial Qty", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.InitialQty, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.QtyAvailable, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.QtyAvailable, new { @class = "form-control", @placeholder = "Qty Available", id = "quantity", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.QtyAvailable, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUOM, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.CostPerUOM, new { @class = "form-control", @placeholder = "Cost Per UOM", id = "price" })
            @Html.ValidationMessageFor(model => model.CostPerUOM, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TotalCost, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.TotalCost, new { @class = "form-control", @placeholder = "Total Cost", @readonly = "readonly", id = "total" })
            @Html.ValidationMessageFor(model => model.TotalCost, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ReceivedBy, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ReceivedBy, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateReceived, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.DateReceived, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", @placeholder = "Notes", @rows = "3" })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <span><input class="btn btn-success" type="submit" value="Save" />&nbsp;</span>
            <span><input class="btn btn-danger" type="reset" value="Cancel" onclick="location.href='@Url.Action("List", "StockItems")'" /></span>
        </div>
    </form>
</div>

Views/StockItems/List.cshtml
@model IEnumerable<Stockzilla.Models.StockItem>
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Stock - Stockzilla";
    ViewBag.Header = "Stock";
}

<script type="text/javascript" class="init">

    $(document).ready(function () {
        $('#datatbl').DataTable();
    });

</script>

<div id='SuccessMsg' class='alert alert-dismissible alert-success' @ViewBag.SuccessMsg>
    <button type='button' class='close' data-dismiss='alert'>&times;</button>
    <p>Your Stock record has been saved successfully.</p>
</div>

<hr />
<div>
    <table id="datatbl" class="table table-striped table-bordered table-hover" cellspacing="0" col-md-10 col-md-offset-1>
        <thead>
            <tr>
                <th></th>
                <th>GRN No.</th>  
                <th>Product Code</th>
                <th>Location</th>
                <th>Batch No.</th>
                <th>Serial No.</th>
                <th>Qty Available</th>
                <th>Date Received</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center"><a class="btn btn-xs btn-info" asp-controller="stockitems" asp-action="edit" asp-route-id="@item.StockId"><span><i class="fa fa-edit" title="Edit"></i></span></a></td>
                    <td>@item.GRNNo </td>
                    <td>
                        @if (item.Product != null)
                        {
                            @item.Product.ProductCode
                        }
                    </td>
                    <td>
                        @if (item.Location != null)
                        {
                            @item.Location.Name
                        }
                    </td>
                    <td>@item.BatchNo</td>
                    <td>@item.SerialNo</td>
                    <td>@item.QtyAvailable</td>
                    <td>@item.DateReceived</td>
                </tr>
            }
        </tbody>
    </table>
</div>