Controllers/LocationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Location Methods throughout the app.
    /// </summary>
    public class LocationsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public LocationsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Location View.
        /// </summary>
        /// <returns>Add Location View</returns>
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid.  Method then get the User and Site Id and creates a new Location for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Location View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(Location model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddLocation(model);
                ModelState.Clear();
                return RedirectToAction("list", new { id = "success" });
            }

            return View();
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Location ID and Site Id and loads the data into a Category Model and passes the Model into the Edit Location View for edit.
        /// </summary>
        /// <returns>Edit Category View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();
                Location model = _repository.GetLocation(key, siteId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Location View</returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(Location model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveLocation(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Location data grid.
        /// </summary>
        /// <returns>Location List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllLocations(siteId);
            return View(data);
        }

        #endregion
      
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Product Methods throughout the app.
    /// </summary>
    public class ProductsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public ProductsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Product View.
        /// </summary>
        /// <returns>Add Product View</returns>
        [Authorize]
        public async Task<IActionResult> Add()
        {
            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            //Loads the dropdown data
            ViewBag.CategoryId = new SelectList(_repository.GetAllCategories(siteId), "CategoryId", "Name");
            ViewBag.UOMId = new SelectList(_repository.GetAllUOMs(siteId), "UOMId", "Name");
            ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name");

            Product model = new Product();

            return View(model);
        }

        /// <summary>
        /// Checks if the Product Model posted back is valid.  Method then get the User and Site Id and creates a new Product for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Model View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(Product model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddProduct(model);
                ModelState.Clear();

                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Product ID and Site Id and loads the data into a Product Model and passes the Model into the Edit Product View for edit.
        /// </summary>
        /// <returns>Edit Product View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();

                Product model = new Product();
                model = _repository.GetProduct(key, siteId);

                //Loads the dropdown data
                ViewBag.CategoryId = new SelectList(_repository.GetAllCategories(siteId), "CategoryId", "Name", model.CategoryId);
                ViewBag.UOMId = new SelectList(_repository.GetAllUOMs(siteId), "UOMId", "Name", model.UOMId);
                ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name", model.LocationId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Product Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Product View</returns>
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Product model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveProduct(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Product data grid.
        /// </summary>
        /// <returns>Product List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllProducts(siteId);
            return View(data);
        }


        #endregion

    }
}

Controllers/StockReceiptsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Stock Receipt Methods throughout the app.
    /// </summary>
    public class StockReceiptsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public StockReceiptsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        /// <summary>
        /// Called by JQuery to load the Default Product Location.  This is triggered when the Product dropwon on the Add View changes.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Json String</returns>
        [HttpGet]
        public JsonResult UpdatePreferredLocation(string id)
        {
            return Json(_repository.GetProductDefaultLocation(id));
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Stock Receipt View.
        /// </summary>
        /// <returns>Add Stock Receipt View</returns>
        [Authorize]
        public async Task<IActionResult> Add()
        {
            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            //Loads the dropdown data
            ViewBag.ProductId = new SelectList(_repository.GetAllProducts(siteId), "ProductId", "ProductCode");
            ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name");

            return View();
        }

        /// <summary>
        /// Checks if the Add Stock Receipt Model posted back is valid.  Method then get the User and Site Id and creates a new Stock Receipt for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Model View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(StockReceipt model)
        {
            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            if (ModelState.IsValid)
            {
                model.SiteId = siteId;
                model.ReceivedBy = user.Name;
                model.DateReceived = DateTime.Now;

                _repository.AddStockReceipt(model);
                CreateStockRecord(model);
                ModelState.Clear();

                return RedirectToAction("list", new { id = "success" });
            }

            //Loads the dropdown data
            ViewBag.ProductId = new SelectList(_repository.GetAllProducts(siteId), "ProductId", "ProductCode");
            ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name");

            return View(model);
        }

        /// <summary>
        /// Creates the stock record on creation of the stock receipt.
        /// </summary>
        /// <param name="stockReceiptModel"></param>
        private void CreateStockRecord(StockReceipt stockReceiptModel)
        {
            string GRNNo = _repository.GetGRN(stockReceiptModel.SiteId);
            //StockItem stockModel = new StockItem { GRNNo = GRNNo, ProductId = stockReceiptModel.ProductId, Product = stockReceiptModel.Product, LocationId= stockReceiptModel.LocationId, Location = stockReceiptModel.Location, SerialNo = stockReceiptModel.SerialNo, BatchNo = stockReceiptModel.BatchNo, DateReceived = stockReceiptModel.DateReceived, ReceivedBy = stockReceiptModel.ReceivedBy, InitialQty = stockReceiptModel.Qty, QtyAvailable = stockReceiptModel.Qty, CostPerUOM = stockReceiptModel.CostPerUOM, TotalCost = stockReceiptModel.TotalCost, Notes=stockReceiptModel.Notes, SiteId = stockReceiptModel.SiteId};
            //_repository.AddStockItem(stockModel);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Stock Receipt data grid.
        /// </summary>
        /// <returns>Stock Receipt List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllStockReceipts(siteId);
            return View(data);
        }



        #endregion    

    }
}

Views/StockReceipts/Add.cshtml
@model Stockzilla.Models.StockReceipt
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Add To Stock - Stockzilla";
    ViewBag.Header = "Add To Stock";
}

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script>


    function CallChangefunc(val) {
 $.ajax({
   url: '@Url.Action("UpdatePreferredLocation", "StockReceipts")',
   type: 'GET',
   dataType: 'json',
   cache: false,
    data: { 'id': val },
        success: function (results) {
            $('#LocationId').val(results);
   },

   });
    }

    </script>
}


<div class="col-md-6 col-md-offset-3">

    <form method="post" novalidate>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, new { @class = "control-label" })
            <div class="input-group">
                @Html.DropDownList("ProductId", null, "Choose Product", new { @class = "form-control", @onchange = "CallChangefunc(this.value)" })
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Products")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, new { @class = "control-label" })
            <div class="input-group">
                @Html.DropDownList("LocationId", null, "Choose Location", new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Locations")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SerialNo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.SerialNo, new { @class = "form-control", @placeholder = "Serial No." })
            @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BatchNo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.BatchNo, new { @class = "form-control", @placeholder = "Batch No." })
            @Html.ValidationMessageFor(model => model.BatchNo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Qty, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.Qty, new { @class = "form-control", @placeholder = "Qty", id = "quantity" })
            @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUOM, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.CostPerUOM, new { @class = "form-control", @placeholder = "Cost Per UOM", id = "price" })
            @Html.ValidationMessageFor(model => model.CostPerUOM, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TotalCost, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.TotalCost, new { @class = "form-control", @placeholder = "Total Cost", @readonly = "readonly", id = "total" })
            @Html.ValidationMessageFor(model => model.TotalCost, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", @placeholder = "Notes", @rows = "3" })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <span><input class="btn btn-success" type="submit" value="Save" />&nbsp;</span>
            <span><input class="btn btn-danger" type="reset" value="Cancel" onclick="location.href='@Url.Action("List", "StockReceipts")'" /></span>
        </div>
    </form>

</div>

Views/StockReceipts/List.cshtml
@model IEnumerable<Stockzilla.Models.StockReceipt>
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Stock Receipts - Stockzilla";
    ViewBag.Header = "Stock Receipts";
}

<script type="text/javascript" class="init">

    $(document).ready(function () {
        $('#datatbl').DataTable();
    });

</script>

<div id='SuccessMsg' class='alert alert-dismissible alert-success' @ViewBag.SuccessMsg>
    <button type='button' class='close' data-dismiss='alert'>&times;</button>
    <p>Your Stock record has been saved successfully.</p>
</div>

<div>
    <input class="btn btn-success" type="submit" value="Add New" onclick="location.href='@Url.Action("Add")'" />
</div>
<hr />
<div>
    <table id="datatbl" class="table table-striped table-bordered table-hover" cellspacing="0" col-md-10 col-md-offset-1>
        <thead>
            <tr>
                <th>Product Code</th>
                <th>Location</th>
                <th>Batch No.</th>
                <th>Serial No.</th>
                <th>Qty</th>
                <th>Date Received</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.Product != null)
                        {
                            @item.Product.ProductCode
                        }
                    </td>
                    <td>
                        @if (item.Location != null)
                        {
                            @item.Location.Name
                        }
                    </td>
                    <td>@item.BatchNo</td>
                    <td>@item.SerialNo</td>
                    <td>@item.Qty</td>
                    <td>@item.DateReceived</td>
                </tr>
            }
        </tbody>
    </table>
</div>