Controllers/LocationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Location Methods throughout the app.
    /// </summary>
    public class LocationsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public LocationsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Location View.
        /// </summary>
        /// <returns>Add Location View</returns>
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid.  Method then get the User and Site Id and creates a new Location for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Location View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(Location model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddLocation(model);
                ModelState.Clear();
                return RedirectToAction("list", new { id = "success" });
            }

            return View();
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Location ID and Site Id and loads the data into a Category Model and passes the Model into the Edit Location View for edit.
        /// </summary>
        /// <returns>Edit Category View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();
                Location model = _repository.GetLocation(key, siteId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Location Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Location View</returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(Location model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveLocation(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Location data grid.
        /// </summary>
        /// <returns>Location List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllLocations(siteId);
            return View(data);
        }

        #endregion
      
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the Product Methods throughout the app.
    /// </summary>
    public class ProductsController : Controller
    {

        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public ProductsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add Product View.
        /// </summary>
        /// <returns>Add Product View</returns>
        [Authorize]
        public async Task<IActionResult> Add()
        {
            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            //Loads the dropdown data
            ViewBag.CategoryId = new SelectList(_repository.GetAllCategories(siteId), "CategoryId", "Name");
            ViewBag.UOMId = new SelectList(_repository.GetAllUOMs(siteId), "UOMId", "Name");
            ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name");

            Product model = new Product();

            return View(model);
        }

        /// <summary>
        /// Checks if the Product Model posted back is valid.  Method then get the User and Site Id and creates a new Product for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Model View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(Product model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddProduct(model);
                ModelState.Clear();

                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the Product ID and Site Id and loads the data into a Product Model and passes the Model into the Edit Product View for edit.
        /// </summary>
        /// <returns>Edit Product View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();

                Product model = new Product();
                model = _repository.GetProduct(key, siteId);

                //Loads the dropdown data
                ViewBag.CategoryId = new SelectList(_repository.GetAllCategories(siteId), "CategoryId", "Name", model.CategoryId);
                ViewBag.UOMId = new SelectList(_repository.GetAllUOMs(siteId), "UOMId", "Name", model.UOMId);
                ViewBag.LocationId = new SelectList(_repository.GetAllLocations(siteId), "LocationId", "Name", model.LocationId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the Product Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Product View</returns>
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Product model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveProduct(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the Product data grid.
        /// </summary>
        /// <returns>Product List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllProducts(siteId);
            return View(data);
        }


        #endregion

    }
}

Controllers/UOMController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stockzilla.Models;
using Stockzilla.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stockzilla.Controllers
{
    /// <summary>
    /// This controller controls the UOM Methods throughout the app.
    /// </summary>
    public class UOMsController : Controller
    {
        #region "Constuctors/Variables/Misc"

        StockzillaRespository _repository;
        private readonly UserManager<StockzillaUser> _userManager;
        private readonly SignInManager<StockzillaUser> _signInManager;

        /// <summary>
        /// Constructor to inject User Manager, SignIn Manager & EF Repository Service.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="userManager"></param>
        /// <param name="signInManager"></param>
        public UOMsController(StockzillaRespository repository, UserManager<StockzillaUser> userManager, SignInManager<StockzillaUser> signInManager)
        {
            _repository = repository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Gets the current user logged in.
        /// </summary>
        /// <returns>User</returns>
        private Task<StockzillaUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion

        #region "Add"

        /// <summary>
        /// Returns an empty Add UOM View.
        /// </summary>
        /// <returns>Add UOM View</returns>
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Checks if the UOM Model posted back is valid.  Method then get the User and Site Id and creates a new UOM for that particular site.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Add Location View</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(UOM model)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;
                model.SiteId = siteId;
                model.CreatedBy = user.Name;
                model.CreatedDate = DateTime.Now;

                _repository.AddUOM(model);
                ModelState.Clear();
                return RedirectToAction("list", new { id = "success" });
            }

            return View();
        }

        #endregion

        #region "Edit"

        /// <summary>
        /// Checks the UOM ID and Site Id and loads the data into a UOM Model and passes the Model into the Edit UOM View for edit.
        /// </summary>
        /// <returns>Edit Category View</returns>
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            if (RouteData.Values.ContainsKey("Id"))
            {
                var user = await GetCurrentUserAsync();
                var siteId = user.SiteID;

                string key;
                key = RouteData.Values["Id"].ToString();
                UOM model = _repository.GetUOM(key, siteId);

                return View(model);
            }
            else
            {
                return RedirectToAction("list");
            }
        }

        /// <summary>
        /// Checks if the UOM Model posted back is valid and saves the data.
        /// </summary>
        /// <param name="model"></param>
        /// <returns>UOM View</returns>
        [Authorize]
        [HttpPost]
        public IActionResult Edit(UOM model)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveUOM(model);
                return RedirectToAction("list", new { id = "success" });
            }

            return View(model);
        }

        #endregion

        #region "List"

        /// <summary>
        /// Loads the UOM data grid.
        /// </summary>
        /// <returns>UOM List View</returns>
        [Authorize]
        public async Task<IActionResult> List()
        {
            //SuccessMsg is used to hide or display the data saved alert notification.
            @ViewBag.SuccessMsg = "hidden";

            if (RouteData.Values.ContainsKey("Id"))
            {
                string key;
                key = RouteData.Values["Id"].ToString();
                if (key == "success")
                {
                    @ViewBag.SuccessMsg = "";
                }
            }

            var user = await GetCurrentUserAsync();
            var siteId = user.SiteID;

            var data = _repository.GetAllUOMs(siteId);
            return View(data);
        }

        #endregion

    }
}

Views/Products/Add.cshtml
@model Stockzilla.Models.Product
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Add Product - Stockzilla";
    ViewBag.Header = "Add Product";
}

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-7 col-md-offset-3">
    <form method="post" novalidate>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ProductCode, new { @class = "form-control", @placeholder = "Product Code" })
            @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "Description", @rows = "3" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, new { @class = "control-label" })
            <div class="input-group">
                @Html.DropDownList("CategoryId", null, "Choose Category", new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Categories")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UOMId, new { @class = "control-label" })
            <div class="input-group">
                @Html.DropDownList("UOMId", null, "Choose Unit of Measure", new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "UOMs")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Traceability, new { @class = "control-label" })
            @Html.DropDownList("Traceability", new SelectList(
                    new List<Object>{
                        new { value = "FIFO" , text = "FIFO" },
                        new { value = "LIFO" , text = "LIFO" },
                         new { value = "Batch" , text = "Batch" },
                         new { value = "Serial" , text = "Serial"}
                      },
                    "value",
                    "text",
                     2), "Choose Traceability", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Traceability, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId,"Default Location", new { @class = "control-label" })
            <div class="input-group">
                @Html.DropDownList("LocationId", null, "Choose Default Location", new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Locations")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">

            @Html.LabelFor(model => model.ReorderLevel, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ReorderLevel, new { @class = "form-control", @placeholder = "Stock Reorder Level" })
            @Html.ValidationMessageFor(model => model.ReorderLevel, "", new { @class = "text-danger"})
        </div>
        <div class="form-group">
            <span><input class="btn btn-success" type="submit" value="Save" />&nbsp;</span>
            <span><input class="btn btn-danger" type="reset" value="Cancel" onclick="location.href='@Url.Action("List", "Products")'" /></span>
        </div>
    </form>
</div>

Views/Products/Edit.cshtml
@model Stockzilla.Models.Product
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Edit Product - Stockzilla";
    ViewBag.Header = "Edit Product";
}

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 col-md-offset-3">
    <form method="post" novalidate>
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.SiteId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ProductCode, new { @class = "form-control", @placeholder = "Product Code" })
            @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "Description", @rows = "3" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, new { @class = "control-label" })
            <div class="input-group">
                @if (Model.CategoryId != null)
            {
                    @Html.DropDownList("CategoryId", null, "Choose Category", new { @class = "form-control", value = Model.Category.Name })
                }
                else
                {
                    @Html.DropDownList("CategoryId", null, "Choose Category", new { @class = "form-control" })
                }
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Categories")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UOMId, new { @class = "control-label" })
            <div class="input-group">
                @if (Model.UOMId != null)
            {
                    @Html.DropDownList("UOMId", null, "Choose Unit of Measure", new { @class = "form-control", value = Model.UOM.Name })
                }
                else
                {
                    @Html.DropDownList("UOMId", null, "Choose Unit of Measure", new { @class = "form-control" })
                }
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "UOMs")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Traceability, new { @class = "control-label" })
            @Html.DropDownList("Traceability", new SelectList(
                    new List<Object>{
                        new { value = "FIFO" , text = "FIFO" },
                        new { value = "LIFO" , text = "LIFO" },
                         new { value = "Batch" , text = "Batch" },
                         new { value = "Serial" , text = "Serial"}
                      },
                    "value",
                    "text",
                     2), "Choose Traceability", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Traceability, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "Default Location", new { @class = "control-label" })
            <div class="input-group">
                @if (Model.LocationId != null)
            {
                    @Html.DropDownList("LocationId", null, "Choose Default Location", new { @class = "form-control", value = Model.Location.Name })
                }
                else
                {
                    @Html.DropDownList("LocationId", null, "Choose Default Location", new { @class = "form-control" })
                }
                <span class="input-group-btn">
                    <button class="btn btn-toolbar" type="button" onclick="location.href='@Url.Action("Add", "Locations")'"><i class="fa fa-plus-circle"></i></button>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ReorderLevel, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ReorderLevel, new { @class = "form-control", @placeholder = "Stock Reorder Level" })
            @Html.ValidationMessageFor(model => model.ReorderLevel, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.CreatedDate, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group">
            <span><input class="btn btn-success" type="submit" value="Save" />&nbsp;</span>
            <span><input class="btn btn-danger" type="reset" value="Cancel" onclick="location.href='@Url.Action("List", "Products")'" /></span>
        </div>
    </form>
</div>

Views/Products/List.cshtml
@model IEnumerable<Stockzilla.Models.Product>
@{
    Layout = "_Layout_Signed_In";
    ViewBag.Title = "Products - Stockzilla";
    ViewBag.Header = "Products";
}

<script type="text/javascript" class="init">

    $(document).ready(function () {
        $('#datatbl').DataTable();
    });
</script>

<div id='SuccessMsg' class='alert alert-dismissible alert-success' @ViewBag.SuccessMsg>
    <button type='button' class='close' data-dismiss='alert'>&times;</button>
    <p>Your Product record has been saved successfully.</p>
</div>

<div>
    <input class="btn btn-success" type="submit" value="Add New" onclick="location.href='@Url.Action("Add")'" />
</div>
<hr />
<div>
    <table id="datatbl" class="table table-striped table-bordered table-hover" cellspacing="0" col-md-10 col-md-offset-1>
        <thead>
            <tr>
                <th></th>
                <th>Product Code</th>
                <th>Description</th>
                <th>Category</th>
                <th>UOM</th>
                <th>Traceability</th>
                <th>Default Location</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center"><a class="btn btn-xs btn-info" asp-controller="products" asp-action="edit" asp-route-id="@item.ProductId"><span><i class="fa fa-edit" title="Edit"></i></span></a></td>
                    <td>@item.ProductCode</td>
                    <td>@item.Description</td>
                    <td>
                        @if (item.Category != null)
                        {
                            @item.Category.Name
                        }
                    </td>
                    <td>
                        @if (item.UOM != null)
                        {
                            @item.UOM.Name
                        }
                    </td>
                    <td>@item.Traceability</td>
                    <td>
                        @if (item.Location != null)
                        {
                            @item.Location.Name
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>